--
name: dev
credential:
  user: tvu
server:
  deploy_dir: /nfs/public/rw/webadmin/tomcat/bases/pride/tc-pst-prider-ws_test/deploy
  user: tc_pst02
  deploy_user: pst_prd
  deploy_prefix: ddi-web-service
  symlink_default_war: /nfs/public/rw/webadmin/tomcat/bases/pride/tc-pst-prider-ws_test/deploy/ddi-webservice.war
  hosts:
    - ves-hx-43
java:
  start: /nfs/public/rw/webadmin/tomcat/bases/pride/tc-pst-prider-ws_test/bin/start
  clean_dir: /nfs/public/rw/webadmin/tomcat/bases/pride/tc-pst-prider-ws_test/bin/clean_dirs
  stop: /nfs/public/rw/webadmin/tomcat/bases/pride/tc-pst-prider-ws_test/bin/stop
middware:
  host: ebi-cli
  tmp_dir: /tmp/omicsdi/ddi-web-service
